### ISSUE TITLE
~/.hyperterm_plugins/.hyperterm-sync-settings.json doesn't exist

### ISSUE THREAD

**Issue by ryanaltvater** [dfrankland/hyper-sync-settings#13] opened 2016-09-22 18:27 UTC
I've added `hyperterm-sync-settings` to `~/.hyperterm.js`, but for some reason `~/.hyperterm_plugins/.hyperterm-sync-settings.json` doesn't exist. Therefore, I cannot proceed setting up this plugin.

I am on macOS Sierra.

**Comment by dfrankland** [comment] 2016-09-22 18:32
That's strange. Feel free to just create the file with the below JSON:

``` json
{
  "personalAccessToken": "ReallyLongAccessToken",
  "gistId": "ReallyLongGistId"
}
```

Everything should work then 👍

**Comment by ryanaltvater** [comment] 2016-09-22 18:36
Well, I guess I could do that, but I don't even see anything installed under `node_modules` for this plugin.

This is the notification that I get when adding `hyperterm-sync-settings` to HyperTerm's plugin list, and then save that file...

<img width="373" alt="screen shot 2016-09-22 at 2 37 41 pm" src="https://cloud.githubusercontent.com/assets/1336787/18761245/27f10a6a-80d2-11e6-8209-cc9d949b89e6.png">

This is the console error under DevTools...

<img width="550" alt="screen shot 2016-09-22 at 2 39 40 pm" src="https://cloud.githubusercontent.com/assets/1336787/18761318/6c9024f8-80d2-11e6-9b7d-e0232cc1cb63.png">

**Comment by ryanaltvater** [comment] 2016-09-22 18:39
This is the notification that I get when adding `hyperterm-sync-settings` to HyperTerm's plugin list, and then save that file.

<img width="373" alt="screen shot 2016-09-22 at 2 37 41 pm" src="https://cloud.githubusercontent.com/assets/1336787/18761245/27f10a6a-80d2-11e6-8209-cc9d949b89e6.png">

**Comment by ryanaltvater** [comment] 2016-09-22 18:39
<img width="550" alt="screen shot 2016-09-22 at 2 39 40 pm" src="https://cloud.githubusercontent.com/assets/1336787/18761318/6c9024f8-80d2-11e6-9b7d-e0232cc1cb63.png">

**Comment by dfrankland** [comment] 2016-09-22 18:49
I haven't tested on macOS Sierra yet, but I don't think that's the issue. Have you tried the fixes in the other issues created?

Can you try to quit out of HyperTerm and then try again doing "Plugins > Update All Now" from the menu?

**Comment by ryanaltvater** [comment] 2016-09-22 19:06
I don't think those other issues are relevant to my issue, since I can't even get the plugin to install in `node_modules`. I have quit HyperTerm many times and also tried updating the plugins. I just get a notification of "No changes!".

I just uninstalled and reinstalled HyperTerm, and removed HyperTerm-related files. Still the same issue. I've attached the log file.

[npm-debug.txt](https://github.com/dfrankland/hyperterm-sync-settings/files/488149/npm-debug.txt)

**Comment by dfrankland** [comment] 2016-09-22 19:41
This is defintely an issue with [`nodegit`](https://github.com/nodegit/nodegit). Looking at your npm-debug.txt, at the bottom the relevant error is this:

```
22446 error Darwin 16.0.0
22447 error argv "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/bin/npm" "install" "--production"
22448 error node v6.4.0
22449 error npm  v3.10.3
22450 error code ELIFECYCLE
22451 error nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
22451 error Exit status 1
22452 error Failed at the nodegit@0.15.1 preinstall script 'node lifecycleScripts/preinstall'.
```

Now looking over at the [`install` script for `nodegit`](https://github.com/nodegit/nodegit/blob/master/package.json#L75) you'll see:

``` json
...
"install": "node lifecycleScripts/preinstall && node lifecycleScripts/install",
...
```

**This actually might be an incompatibility with macOS Sierra 😱**

Is it possible for you to try to install [`nodegit`](https://github.com/nodegit/nodegit) in any folder by doing the following?

``` bash
npm i nodegit
```

If it fails, then we know where the problem is...

**Comment by ryanaltvater** [comment] 2016-09-22 19:50
npm WARN enoent ENOENT: no such file or directory, open '/Users/realtvater/Sites/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/bin/npm" "i" "nodegit"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/realtvater/Sites/test/npm-debug.log

**Comment by dfrankland** [comment] 2016-09-22 19:52
Yep, there's an issue on macOS Sierra with `nodegit`.
Please check this issue here: https://github.com/nodegit/nodegit/issues/1124

**Comment by ryanaltvater** [comment] 2016-09-22 19:54
Awesome! 👍 lol

**Comment by dfrankland** [comment] 2016-11-07 22:43
This should get fixed with [this PR](https://github.com/zeit/hyper/pull/970) and the next release, closing for now.

**Closed as completed by dfrankland** 2016-11-07 22:43 UTC
