### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by RobbieTheWagner** [dfrankland/hyper-sync-settings#5] opened 2016-07-25 20:57 UTC
Getting errors when trying to use this plugin. `Error: Cannot find module '../build/Debug/nodegit.node'` What should I do?

**Comment by RobbieTheWagner** [comment] 2016-07-25 21:26
I manually did `npm install --save hyperterm-sync-settings` and the error went away, but the plugin doesn't seem to work.

**Comment by dfrankland** [comment] 2016-07-26 00:33
What version of HyperTerm are you running? And how did you install this module (`git clone`, `npm install`, or just put `hyperterm-sync-settings` in your `~/.hyperterm.js` file)?

**Comment by RobbieTheWagner** [comment] 2016-07-26 01:28
I'm on the latest HyperTerm, built from the master branch. I tried installing just by adding to the `plugins` array.

**Comment by dfrankland** [comment] 2016-07-26 03:57
After further research this seems like an error caused by [`nodegit`](https://github.com/nodegit/nodegit) not building properly :(

I have to investigate how to force installing the prebuilt version of [`nodegit`](https://github.com/nodegit/nodegit)...

So far only using the [`.npmrc`](https://github.com/dfrankland/hyperterm-sync-settings/blob/master/.npmrc) is working.

**Comment by dfrankland** [comment] 2016-07-26 04:19
I found the issue! This commit is what is breaking  [`nodegit`](https://github.com/nodegit/nodegit) :

https://github.com/zeit/hyperterm/commit/bd5e802e1fb76d36955aae9359f829b3b7f8ce4e

[`nodegit`](https://github.com/nodegit/nodegit)  requires running extra pre- and post-install scripts. I'll have to open an issue up on [`hyperterm`](https://github.com/zeit/hyperterm) about this issue...

**Comment by dfrankland** [comment] 2016-07-26 04:27
I've opened an issue about this problem here: https://github.com/zeit/hyperterm/issues/408

**Comment by dfrankland** [comment] 2016-07-26 18:17
Looks like this will be closed soon: https://github.com/zeit/hyperterm/issues/411#issuecomment-235349425

**Comment by dfrankland** [comment] 2016-07-26 20:46
Fixed with this revert https://github.com/zeit/hyperterm/commit/05b491f62c43db100316176b9bb0d8e50487b902!

Please upgrade to [HyperTerm 0.7.1](https://github.com/zeit/hyperterm/releases/tag/v0.7.1) or newer 👍

**Closed as completed by dfrankland** 2016-07-26 20:46 UTC

**Comment by RobbieTheWagner** [comment] 2016-07-26 22:39
Thanks!

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:05
Still getting this error @dfrankland 😞

**Comment by dfrankland** [comment] 2016-07-27 19:24
Did you do a fresh install of the module? As in did you remove `~/.hyperterm_plugins/node_modules`, quit and restart HyperTerm, then run `Plugins > Updated All Now`?

Simply upgrading is not enough to fix this issue because it occurs when `nodegit` gets compiled as a dependency.

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:26
@dfrankland I didn't do those specific steps, but I did `rm -rf node_modules` and then I did `npm i`. That didn't work though. Trying your specific steps now

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:26
I'm not sure how to know when plugins updating is done. There is no progress bar or anything

**Comment by dfrankland** [comment] 2016-07-27 19:30
Yep, running `npm i` is not enough, because there are environmental variables that need to get set for `nodegit` to install properly; HyperTerm sets these when installing plugins via its `Plugins > Update All Now` command.

As far as a progress bar goes, that should be a feature that HyperTerm should add 💭  It shouldn't take too long though, maybe 2-5 minutes.

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:31
@dfrankland all your suggestion seems to have done for me was make all of my plugins break :(

**Comment by dfrankland** [comment] 2016-07-27 19:32
Yes, of course they will "break" because you just removed them from `~/.hyperterm_plugins/node_modules`, after you run `Plugins > Update All Now` they will be re-installed.

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:33
The update doesn't seem to do anything. No idea if I need to just wait for hours or what, since there is no progress bar. Let it sit for quite awhile

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:34
Will it say updates have completed?

**Comment by dfrankland** [comment] 2016-07-27 19:35
It won't give you a notice unfortunately, but if you try to run `Plugins > Update All Now` again it will tell you whether there is an update currently running or if there are no upgrades available.

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:47
@dfrankland I finally got an error updating after a long time of waiting

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:49
@dfrankland could you make the environment variables stuff happen preinstall, so I could just  `npm i`?

**Comment by RobbieTheWagner** [comment] 2016-07-27 19:51
My hyperterm is totally jacked. Going to need to completely start fresh. No matter what I do, I can't even install a theme now. I do not recommend doing the instructions you listed.

**Comment by dfrankland** [comment] 2016-07-27 19:59
To emulate what [HyperTerm is doing to set the environmental variables](https://github.com/zeit/hyperterm/blob/master/app/plugins.js#L203), you can install using `npm` like this:

``` bash
npm_config_runtime="electron" \
npm_config_target="1.2.8" \
npm_config_disturl="https://atom.io/download/atom-shell" \
npm i
```

HyperTerm literally can't be "jacked" by removing its plugin dependencies, they just get re-downloaded again afterwards, it in no way affects any configuration that you may have, unless you are editing files in your dependencies, which would not be highly recommended.

I have followed the above steps, ad nauseam, during development and debugging without any issues so far.

**Comment by RobbieTheWagner** [comment] 2016-07-27 21:01
They are not downloaded again though. No plugins work anymore. I was able to fix it by removing hyperterm, and installing with homebrew instead.
